import { strict as assert } from "node:assert";
import test from "node:test";
import { renderIntentStudioPage } from "./render-intent-studio-page";

test("renderIntentStudioPage Given the default studio shell When rendered Then it includes the dark mode toggle and closes the HTML document", () => {
  const html = renderIntentStudioPage({ configPath: "intent-poc.local-no-linear.yaml" });
  const promptInputIndex = html.indexOf('id="prompt-input"');
  const submitButtonIndex = html.indexOf('id="submit-button"');
  const workScopeIndex = html.indexOf('id="work-scope-panel"');
  const stepsPanelIndex = html.indexOf('id="steps-panel"');

  assert.match(html, /<button class="dark-mode-toggle" id="dark-mode-toggle">Toggle Dark Mode<\/button>/);
  assert.match(html, /function setDarkMode\(enabled, syncUrl\) \{/);
  assert.match(html, /url\.searchParams\.set\("dark", "true"\);/);
  assert.match(html, /syncDarkModeFromUrl\(\);/);
  assert.match(html, /\.dark-mode textarea,/);
  assert.match(html, /background: rgba\(15, 23, 42, 0\.88\);/);
  assert.match(html, /id="toggle-work-scope-visibility"[^>]*>Collapse<\/button>/);
  assert.match(html, /id="toggle-stages-visibility"[^>]*>Collapse<\/button>/);
  assert.match(html, /wireCollapseToggle\("toggle-work-scope-visibility", "work-scope-panel", "block"\);/);
  assert.match(html, /wireCollapseToggle\("toggle-stages-visibility", "steps-panel", "block"\);/);
  assert.match(html, /id="workflow-readiness-status"/);
  assert.match(html, /id="workflow-readiness-summary"/);
  assert.match(html, /id="workflow-readiness-pipeline"/);
  assert.match(html, /implementation, QA, screenshots, comparison, and artifacts/);
  assert.ok(promptInputIndex >= 0);
  assert.ok(submitButtonIndex > promptInputIndex);
  assert.ok(workScopeIndex > submitButtonIndex);
  assert.ok(stepsPanelIndex > submitButtonIndex);
  assert.match(html, /id="step-bdd"/);
  assert.match(html, /id="plan-criteria"/);
  assert.match(html, /id="step-tdd"/);
  assert.match(html, /id="plan-decomposition"/);
  assert.match(html, /id="plan-work-items"/);
  assert.match(html, /id="selection-title"/);
  assert.match(html, /id="selection-defaults"/);
  assert.equal(html.includes('id="send-draft-button"'), false);
  assert.match(html, /id="reset-intent-button"/);
  assert.match(html, /The first click builds a reviewed IDD draft with repo context, boundaries, baseline, and minimum success\./);
  assert.match(html, /Click Run intent to generate the scoping IDD draft\./);
  assert.match(html, /Scoping IDD draft ready\. Review it, edit it if needed, then click Run intent again to refresh the full reviewed plan and start the session\./);
  assert.match(html, /The reviewed IDD prompt is approved and the timeline will update live\./);
  assert.match(html, /Scoping draft ready\. Running again will refresh it into the full reviewed plan and then start execution from that reviewed plan\./);
  assert.match(html, /Prompt interpretation: live Gemini/);
  assert.match(html, /2\. Repo Context/);
  assert.match(html, /3\. Scope & Boundaries/);
  assert.match(html, /4\. Success Contract/);
  assert.match(html, /5\. Execution Readiness/);
  assert.match(html, /const previewDraftSessionKey = "intent-studio\.active-reviewed-draft-id";/);
  assert.match(html, /function shouldResumeDraft\(activeDraft\) \{/);
  assert.match(html, /resetIntentButton\.addEventListener\("click", function \(\) \{/);
  assert.match(html, /fetch\("\/api\/plan"/);
  assert.match(html, /fetch\("\/api\/drafts\/" \+ encodeURIComponent\(previewDraft\.draftId\)/);
  assert.match(html, /fetch\("\/api\/runs"/);
  assert.match(html, /<\/html>\s*$/);
});