import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. This tracked Playwright spec is regenerated in place when the same intent path is requested.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library";

test.describe("Intent-driven flow for demo-catalog", () => {
  test("Verify expand functionality on demo catalog components", async ({ page }) => {
    await test.step("Intent Studio Prompt Run", async () => {
      await page.goto(new URL("/", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await page.waitForSelector("#prompt-input");
      await expect(page.locator("body"), "The Intent Studio prompt input is visible and ready for interaction.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/demo-catalog-work-2-verify-expand-functionality-on-demo-catalog-components-demo-", "shot-1-verify-expand-functionality-on-demo-catalog-components-intent-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Configuration Section Visible", async () => {
      await page.waitForSelector("#agent-stages-grid");
      const target = page.locator("#agent-stages-grid");
      await expect(target, "The optional configuration section is visible before interaction.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/demo-catalog-work-2-verify-expand-functionality-on-demo-catalog-components-demo-", "shot-2-verify-expand-functionality-on-demo-catalog-components-configuration-visi.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Collapse Optional Configuration", async () => {
      await page.waitForSelector("#toggle-stages-visibility");
      const target = page.locator("#toggle-stages-visibility");
      await expect(target, "The collapse toggle is available for the optional configuration section.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/demo-catalog-work-2-verify-expand-functionality-on-demo-catalog-components-demo-", "shot-3-verify-expand-functionality-on-demo-catalog-components-collapse-toggle.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Configuration Section Collapsed", async () => {
      await page.waitForSelector("#agent-stages-grid", { state: "hidden" });
      const target = page.locator("#agent-stages-grid");
      await expect(target, "The optional configuration section can be hidden before it is expanded again.").toBeHidden();
      const screenshotPath = path.join(screenshotRoot, "bdd/demo-catalog-work-2-verify-expand-functionality-on-demo-catalog-components-demo-", "shot-4-verify-expand-functionality-on-demo-catalog-components-collapsed-state.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Expand Optional Configuration", async () => {
      await page.waitForSelector("#toggle-stages-visibility");
      const target = page.locator("#toggle-stages-visibility");
      await expect(target, "The expand toggle is available when the configuration section is collapsed.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/demo-catalog-work-2-verify-expand-functionality-on-demo-catalog-components-demo-", "shot-5-verify-expand-functionality-on-demo-catalog-components-expand-toggle.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Configuration Section Expanded", async () => {
      await page.waitForSelector("#promptNormalization-enabled");
      const target = page.locator("#promptNormalization-enabled");
      await expect(target, "A generated Playwright spec captures reviewable screenshots so QA can run this verification automatically.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/demo-catalog-work-2-verify-expand-functionality-on-demo-catalog-components-demo-", "shot-6-verify-expand-functionality-on-demo-catalog-components-expanded-state.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
