import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Test Run Indicator", () => {
  test("Verify active test run status", async ({ page }) => {
    await test.step("Load Intent Studio", async () => {
      await page.goto(new URL("/?dark=true", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio loads successfully and is ready for interaction.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "load-intent-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill Prompt", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt is filled to enable the submit button.").toBeVisible();
      await target.fill("Run test indicator verification");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "fill-prompt.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Generate Draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Draft is generated after the first click.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Scoping Draft Ready", async () => {
      const target = page.locator("text=Scoping IDD draft ready.");
      await expect(target, "The scoping draft is ready for approval before execution starts.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "scoping-draft-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Start Execution", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution starts after the second click approves the draft.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "start-execution.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert Indicator Visible", async () => {
      const target = page.locator("[data-testid=\"test-status-indicator\"]");
      await expect(target, "Status indicator component is visible in the header.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "assert-indicator-visible.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert Running State Code", async () => {
      const target = page.locator("text=QA_GENERATED_PLAYWRIGHT_RUNNING");
      await expect(target, "The real running state code is displayed.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-run-status-spec", "assert-running-state-code.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
