import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test, type Page } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

const requiredUiStates = [
  {
    "stateId": "theme-mode",
    "label": "Theme mode",
    "description": "The demo app supports light and dark theme states that materially change contrast, tokens, and screenshot evidence.",
    "requestedValue": "light",
    "activation": [
      {
        "type": "query-param",
        "target": "dark",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": [
          "The demo app now honors the dark query parameter across Studio and library routes for deterministic verification."
        ]
      },
      {
        "type": "ui-control",
        "target": "[data-testid='theme-toggle']",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": [
          "The library surface toggle remains available for manual verification flows."
        ]
      },
      {
        "type": "ui-control",
        "target": "#dark-mode-toggle",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": [
          "Intent Studio keeps an explicit toggle for interactive review during manual sessions."
        ]
      }
    ],
    "verificationStrategies": [
      "ui-interaction-playwright"
    ],
    "notes": [
      "Stateful UI bugs should declare and verify the requested UI state before screenshot evidence is trusted.",
      "Prefer reusable state activation contracts over prompt-specific routing or one-off checkpoint logic.",
      "Theme-sensitive UI bugs require paired light-mode and dark-mode screenshot evidence; do not accept a dark-mode-only capture set.",
      "Verify the active theme state before trusting screenshot comparisons.",
      "Prefer the shared dark query parameter during generated verification so screenshots start in the requested theme.",
      "Dark-theme verification should keep a light-mode reference screenshot alongside the dark-mode target evidence."
    ],
    "reason": "Prompt requests the Theme mode UI state with value \"light\"."
  }
] as const;

function buildUrlWithUiStates(routePath: string, requirements: typeof requiredUiStates): string {
  const url = new URL(routePath, baseUrl);
  for (const requirement of requirements) {
    if (!requirement.requestedValue) {
      continue;
    }

    for (const activation of requirement.activation) {
      if (activation.type !== "query-param" || !activation.target) {
        continue;
      }

      const activationValue = activation.values[requirement.requestedValue];
      if (typeof activationValue === "string" && activationValue.length > 0) {
        url.searchParams.set(activation.target, activationValue);
      }
    }
  }

  return url.toString();
}

function isUiStateRouteSatisfied(page: Page, requirement: (typeof requiredUiStates)[number]): boolean {
  const currentUrl = new URL(page.url());
  for (const activation of requirement.activation) {
    if (activation.type !== "query-param" || !activation.target) {
      continue;
    }

    const activationValue = activation.values[requirement.requestedValue];
    if (typeof activationValue !== "string" || activationValue.length === 0) {
      continue;
    }

    if (currentUrl.searchParams.get(activation.target) === activationValue) {
      return true;
    }
  }

  return false;
}

async function applyUiStateRequirements(page: Page, requirements: typeof requiredUiStates): Promise<void> {
  for (const requirement of requirements) {
    if (!requirement.requestedValue) {
      continue;
    }

    if (isUiStateRouteSatisfied(page, requirement)) {
      continue;
    }

    for (const activation of requirement.activation) {
      if (activation.type !== "ui-control" || !activation.target) {
        continue;
      }

      const activationValue = activation.values[requirement.requestedValue];
      if (!activationValue || !/^(true|1|on|enabled|active)$/i.test(activationValue)) {
        continue;
      }

      const control = page.locator(activation.target).first();
      if ((await control.count()) === 0) {
        continue;
      }

      await expect(control, `${requirement.label ?? requirement.stateId} control should be visible before activation.`).toBeVisible();
      const urlBeforeActivation = page.url();
      await control.click();
      if (page.url() !== urlBeforeActivation) {
        await page.waitForLoadState("load");
      }
      break;
    }
  }
}

test.describe("Intent-driven flow for intent-poc-app", () => {
  test("Displaying the active test run indicator", async ({ page }) => {
    await test.step("Open Intent Studio", async () => {
      await page.goto(buildUrlWithUiStates("/?dark=false", requiredUiStates), { waitUntil: "domcontentloaded" });
      await applyUiStateRequirements(page, requiredUiStates);
      await expect(page.locator("body"), "The Intent Studio prompt input is visible and ready for interaction.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/displaying-the-active-test-run-indicator-spec", "open-intent-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill prompt and initiate run", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt input is filled to enable the run button.").toBeVisible();
      await target.fill("Verify the test indicator");
      const screenshotPath = path.join(screenshotRoot, "bdd/displaying-the-active-test-run-indicator-spec", "fill-prompt-and-initiate-run.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Click run button to generate draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "First click generates the scoping draft.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/displaying-the-active-test-run-indicator-spec", "click-run-button-to-generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Scoping Draft Ready", async () => {
      const target = page.locator("text=Scoping IDD draft ready.");
      await expect(target, "The scoping draft is ready for approval before execution starts.").toBeVisible({ timeout: 30000 });
      const screenshotPath = path.join(screenshotRoot, "bdd/displaying-the-active-test-run-indicator-spec", "scoping-draft-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Click run button to approve draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Second click approves the draft and starts execution.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/displaying-the-active-test-run-indicator-spec", "click-run-button-to-approve-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify indicator visibility and state", async () => {
      const target = page.locator("[data-testid='test-status-indicator']").first();
      await expect(target, "The live indicator exposes the generated Playwright QA state code while verification is running.").toBeVisible();
      const attributeValue = await target.getAttribute("data-state-code");
      expect(attributeValue, "The live indicator exposes the generated Playwright QA state code while verification is running.").toBeTruthy();
      expect(attributeValue ?? "", "The live indicator exposes the generated Playwright QA state code while verification is running.").toContain("QA_GENERATED_PLAYWRIGHT_RUNNING");
      const screenshotPath = path.join(screenshotRoot, "bdd/displaying-the-active-test-run-indicator-spec", "verify-indicator-visibility-and-state.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
