import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Display active test status during execution", async ({ page }) => {
    test.setTimeout(161000);
    await test.step("Navigate to Intent Studio", async () => {
      await page.goto(new URL("/?dark=false", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio is loaded").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "navigate-to-intent-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill prompt", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt input is filled").toBeVisible();
      await target.fill("Run a test suite");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "fill-prompt.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Workflow Readiness Ready", async () => {
      await page.waitForSelector("#workflow-readiness-status", { timeout: 30000 });
      const target = page.locator("#workflow-readiness-status").first();
      await expect(target, "The Studio workflow readiness resolves before the run button is used.").toBeVisible({ timeout: 30000 });
      await expect(target, "The Studio workflow readiness resolves before the run button is used.").toHaveAttribute("class", new RegExp("target-ready"), { timeout: 30000 });
      const attributeValue = await target.getAttribute("class");
      expect(attributeValue, "The Studio workflow readiness resolves before the run button is used.").toBeTruthy();
      expect(attributeValue ?? "", "The Studio workflow readiness resolves before the run button is used.").toContain("target-ready");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "workflow-readiness-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("First click to generate draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Draft generated").toBeVisible();
      await expect(target, "Draft generated").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "first-click-to-generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Scoping Draft Ready", async () => {
      const target = page.locator("text=Scoping IDD draft ready.");
      await expect(target, "The scoping draft is ready for approval before execution starts.").toBeVisible({ timeout: 30000 });
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "scoping-draft-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Second click to approve and execute", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution started").toBeVisible();
      await expect(target, "Execution started").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "second-click-to-approve-and-execute.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert indicator visibility", async () => {
      const target = page.locator("[data-testid='test-status-indicator']");
      await expect(target, "Indicator is visible").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "assert-indicator-visibility.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert running state code", async () => {
      const target = page.locator("[data-testid='test-status-indicator']").first();
      await expect(target, "State code contains RUNNING").toBeVisible({ timeout: 45000 });
      await expect(target, "State code contains RUNNING").toHaveAttribute("data-state-code", new RegExp("RUNNING"), { timeout: 45000 });
      const attributeValue = await target.getAttribute("data-state-code");
      expect(attributeValue, "State code contains RUNNING").toBeTruthy();
      expect(attributeValue ?? "", "State code contains RUNNING").toContain("RUNNING");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-during-execution-spec", "assert-running-state-code.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
