import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Display active test status in Intent Studio", async ({ page }) => {
    await test.step("Navigate to Studio", async () => {
      await page.goto(new URL("/?dark=false", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio is loaded").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "navigate-to-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill prompt", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt input is filled").toBeVisible();
      await target.fill("Run a test suite");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "fill-prompt.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("First click to generate draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Draft generated").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "first-click-to-generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Second click to execute", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution started").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "second-click-to-execute.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert indicator visible", async () => {
      const target = page.locator("[data-testid='test-status-indicator']");
      await expect(target, "Indicator is visible").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "assert-indicator-visible.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert running state", async () => {
      const target = page.locator("[data-testid='test-status-indicator']").first();
      await expect(target, "Indicator shows running").toBeVisible();
      const attributeValue = await target.getAttribute("data-status");
      expect(attributeValue, "Indicator shows running").toBeTruthy();
      expect(attributeValue ?? "", "Indicator shows running").toContain("Running");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "assert-running-state.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert state code", async () => {
      const target = page.locator("[data-testid='test-status-indicator']").first();
      await expect(target, "Indicator shows correct state code").toBeVisible();
      const attributeValue = await target.getAttribute("data-state-code");
      expect(attributeValue, "Indicator shows correct state code").toBeTruthy();
      expect(attributeValue ?? "", "Indicator shows correct state code").toContain("QA_GENERATED_PLAYWRIGHT_RUNNING");
      const screenshotPath = path.join(screenshotRoot, "bdd/display-active-test-status-spec", "assert-state-code.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
