import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent-driven flow for intent-poc-app", () => {
  test("Intent is translated into acceptance-ready work", async ({ page }) => {
    await test.step("Intent Studio Prompt Run", async () => {
      await page.goto(new URL("/", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await page.waitForSelector("#prompt-input");
      await expect(page.locator("body"), "The Intent Studio prompt input is visible and ready for interaction.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/intent-is-translated-into-acceptance-ready-work-spec", "intent-studio-prompt-run.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Configuration Section Visible", async () => {
      await page.waitForSelector("#agent-stages-grid");
      const target = page.locator("#agent-stages-grid");
      await expect(target, "The optional configuration section is visible before interaction.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/intent-is-translated-into-acceptance-ready-work-spec", "configuration-section-visible.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
