import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Login Flow Suite", () => {
  test("Verify successful and failed login", async ({ page }) => {
    test.setTimeout(50000);
    await test.step("Navigate to login", async () => {
      await page.goto(new URL("/", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Login page is visible").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/login-flow-spec", "navigate-to-login.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Enter valid credentials", async () => {
      const target = page.locator("input[name='username']");
      await expect(target, "Credentials entered").toBeVisible();
      await target.fill("");
      const screenshotPath = path.join(screenshotRoot, "bdd/login-flow-spec", "enter-valid-credentials.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Click login button", async () => {
      const target = page.locator("button[type='submit']");
      await expect(target, "Login submitted").toBeVisible();
      await expect(target, "Login submitted").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/login-flow-spec", "click-login-button.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify dashboard redirect", async () => {
      const target = page.locator(".dashboard-container");
      await expect(target, "Dashboard is visible").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/login-flow-spec", "verify-dashboard-redirect.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify error on invalid login", async () => {
      const target = page.locator(".error-message");
      await expect(target, "Error message is displayed").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/login-flow-spec", "verify-error-on-invalid-login.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
