import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Verify status indicator in completion state", async ({ page }) => {
    await test.step("Navigate to Studio", async () => {
      await page.goto(new URL("/?dark=false", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio is loaded").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/status-indicator-complete-spec", "navigate-to-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill prompt", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt input is filled").toBeVisible();
      await target.fill("Run a test");
      const screenshotPath = path.join(screenshotRoot, "bdd/status-indicator-complete-spec", "fill-prompt.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Trigger execution", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution triggered").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/status-indicator-complete-spec", "trigger-execution.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Confirm execution", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution confirmed").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/status-indicator-complete-spec", "confirm-execution.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify completion", async () => {
      const target = page.locator("[data-testid='test-status-indicator']");
      await expect(target, "Indicator shows completion state").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/status-indicator-complete-spec", "verify-completion.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
