import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test, type Page } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

const requiredUiStates = [
  {
    "stateId": "theme-mode",
    "label": "Theme mode",
    "description": "The demo app supports light and dark theme states that materially change contrast, tokens, and screenshot evidence.",
    "requestedValue": "light",
    "activation": [
      {
        "type": "query-param",
        "target": "dark",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": [
          "The demo app now honors the dark query parameter across Studio and library routes for deterministic verification."
        ]
      },
      {
        "type": "ui-control",
        "target": "[data-testid='theme-toggle']",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": [
          "The library surface toggle remains available for manual verification flows."
        ]
      },
      {
        "type": "ui-control",
        "target": "#dark-mode-toggle",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": [
          "Intent Studio keeps an explicit toggle for interactive review during manual sessions."
        ]
      }
    ],
    "verificationStrategies": [
      "ui-interaction-playwright"
    ],
    "notes": [
      "Stateful UI bugs should declare and verify the requested UI state before screenshot evidence is trusted.",
      "Prefer reusable state activation contracts over prompt-specific routing or one-off checkpoint logic.",
      "Theme-sensitive UI bugs require paired light-mode and dark-mode screenshot evidence; do not accept a dark-mode-only capture set.",
      "Verify the active theme state before trusting screenshot comparisons.",
      "Prefer the shared dark query parameter during generated verification so screenshots start in the requested theme.",
      "Dark-theme verification should keep a light-mode reference screenshot alongside the dark-mode target evidence."
    ],
    "reason": "Prompt requests the Theme mode UI state with value \"light\"."
  }
] as const;

function buildUrlWithUiStates(routePath: string, requirements: typeof requiredUiStates): string {
  const url = new URL(routePath, baseUrl);
  for (const requirement of requirements) {
    if (!requirement.requestedValue) {
      continue;
    }

    for (const activation of requirement.activation) {
      if (activation.type !== "query-param" || !activation.target) {
        continue;
      }

      const activationValue = activation.values[requirement.requestedValue];
      if (typeof activationValue === "string" && activationValue.length > 0) {
        url.searchParams.set(activation.target, activationValue);
      }
    }
  }

  return url.toString();
}

function isUiStateRouteSatisfied(page: Page, requirement: (typeof requiredUiStates)[number]): boolean {
  const currentUrl = new URL(page.url());
  for (const activation of requirement.activation) {
    if (activation.type !== "query-param" || !activation.target) {
      continue;
    }

    const activationValue = activation.values[requirement.requestedValue];
    if (typeof activationValue !== "string" || activationValue.length === 0) {
      continue;
    }

    if (currentUrl.searchParams.get(activation.target) === activationValue) {
      return true;
    }
  }

  return false;
}

async function applyUiStateRequirements(page: Page, requirements: typeof requiredUiStates): Promise<void> {
  for (const requirement of requirements) {
    if (!requirement.requestedValue) {
      continue;
    }

    if (isUiStateRouteSatisfied(page, requirement)) {
      continue;
    }

    for (const activation of requirement.activation) {
      if (activation.type !== "ui-control" || !activation.target) {
        continue;
      }

      const activationValue = activation.values[requirement.requestedValue];
      if (!activationValue || !/^(true|1|on|enabled|active)$/i.test(activationValue)) {
        continue;
      }

      const control = page.locator(activation.target).first();
      if ((await control.count()) === 0) {
        continue;
      }

      await expect(control, `${requirement.label ?? requirement.stateId} control should be visible before activation.`).toBeVisible();
      const urlBeforeActivation = page.url();
      await control.click();
      if (page.url() !== urlBeforeActivation) {
        await page.waitForLoadState("load");
      }
      break;
    }
  }
}

test.describe("Intent Studio Run Indicator", () => {
  test("Verify real-time status indicator and state codes", async ({ page }) => {
    await test.step("Open Intent Studio in Light Mode", async () => {
      await page.goto(buildUrlWithUiStates("/?dark=false", requiredUiStates), { waitUntil: "domcontentloaded" });
      await applyUiStateRequirements(page, requiredUiStates);
      await expect(page.locator("body"), "The Intent Studio interface is loaded in light mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "open-intent-studio-in-light-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Enter Prompt", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "The prompt input is populated to enable the run button.").toBeVisible();
      await target.fill("");
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "enter-prompt.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Generate Scoping Draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "The first click generates the scoping draft.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "generate-scoping-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Start Test Execution", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "The second click starts the actual test execution.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "start-test-execution.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify Indicator Visibility", async () => {
      const target = page.locator("[data-testid=\"test-status-indicator\"]");
      await expect(target, "The test status indicator is visible during execution.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "verify-indicator-visibility.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify QA State Code", async () => {
      const target = page.locator("[data-testid=\"test-status-indicator\"]").first();
      await expect(target, "The indicator displays the correct running state code.").toBeVisible();
      const attributeValue = await target.getAttribute("data-state-code");
      expect(attributeValue, "The indicator displays the correct running state code.").toBeTruthy();
      expect(attributeValue ?? "", "The indicator displays the correct running state code.").toContain("QA_GENERATED_PLAYWRIGHT_RUNNING");
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "verify-qa-state-code.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify Global Status Pill", async () => {
      const target = page.locator("#current-status-pill").first();
      await expect(target, "The current status pill reflects the running state.").toBeVisible();
      const attributeValue = await target.getAttribute("class");
      expect(attributeValue, "The current status pill reflects the running state.").toBeTruthy();
      expect(attributeValue ?? "", "The current status pill reflects the running state.").toContain("status-running");
      const screenshotPath = path.join(screenshotRoot, "bdd/test-run-indicator-flow-spec", "verify-global-status-pill.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
