import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Verify indicator reflects running state", async ({ page }) => {
    await test.step("Navigate to Intent Studio", async () => {
      await page.goto(new URL("/", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio is loaded").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "navigate-to-intent-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill prompt to enable run", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt input is populated").toBeVisible();
      await target.fill("Generate a test for the login flow");
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "fill-prompt-to-enable-run.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("First click to generate draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Draft generated").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "first-click-to-generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Scoping Draft Ready", async () => {
      const target = page.locator("text=Scoping IDD draft ready.");
      await expect(target, "The scoping draft is ready for approval before execution starts.").toBeVisible({ timeout: 30000 });
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "scoping-draft-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Second click to execute", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution started").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "second-click-to-execute.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert running state indicator", async () => {
      const target = page.locator("[data-testid='test-status-indicator']");
      await expect(target, "Indicator shows running state").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "assert-running-state-indicator.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert state code", async () => {
      const target = page.locator("#current-status-pill").first();
      await expect(target, "State code is present").toBeVisible();
      const attributeValue = await target.getAttribute("data-state-code");
      expect(attributeValue, "State code is present").toBeTruthy();
      expect(attributeValue ?? "", "State code is present").toContain("QA_GENERATED_PLAYWRIGHT_RUNNING");
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-execution-spec", "assert-state-code.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
