import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator Theme", () => {
  test("Verify indicator contrast in light and dark modes", async ({ page }) => {
    test.setTimeout(30000);
    await test.step("Toggle dark mode", async () => {
      const target = page.locator("#dark-mode-toggle");
      await expect(target, "Dark mode enabled").toBeVisible();
      await expect(target, "Dark mode enabled").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-theme-spec", "toggle-dark-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Verify indicator visibility in dark mode", async () => {
      const target = page.locator("[data-testid='test-status-indicator']");
      await expect(target, "Indicator is visible in dark mode").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/test-status-indicator-theme-spec", "verify-indicator-visibility-in-dark-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
