import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. This tracked Playwright spec is regenerated in place when the same intent path is requested.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library";

test.describe("Intent-driven flow for intent-poc-app", () => {
  test("Verify dark mode input field readability", async ({ page }) => {
    await test.step("Input Field", async () => {
      await page.goto(new URL("/library/primitive-input-field", baseUrl).toString(), { waitUntil: "load" });
      await page.waitForSelector("[data-testid='primitive-input-field']");
      const target = page.locator("[data-testid='primitive-input-field']");
      await expect(target, "The target '[data-testid='primitive-input-field']' is visible for Input Field.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/intent-poc-app-verify-dark-mode-input-field-readability-spec", "shot-1-primitive-input-field.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await target.screenshot({ path: screenshotPath });
    });
  });
});
