import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Verify indicator visual consistency across themes", async ({ page }) => {
    test.setTimeout(36000);
    await test.step("Navigate to Studio in light mode", async () => {
      await page.goto(new URL("/?dark=false", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio loaded in light mode").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-consistency-across-themes-spec", "navigate-to-studio-in-light-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Toggle to dark mode", async () => {
      const target = page.locator("#dark-mode-toggle");
      await expect(target, "Theme toggled to dark").toBeVisible();
      await expect(target, "Theme toggled to dark").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-consistency-across-themes-spec", "toggle-to-dark-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert indicator visibility in dark mode", async () => {
      const target = page.locator("[data-testid='test-status-indicator']");
      await expect(target, "Indicator is visible in dark mode").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-consistency-across-themes-spec", "assert-indicator-visibility-in-dark-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
