import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Verify status indicator visual consistency", async ({ page }) => {
    test.setTimeout(55000);
    await test.step("Navigate to Studio in light mode", async () => {
      await page.goto(new URL("/?dark=false", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio is loaded in light mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-visual-consistency-spec", "navigate-to-studio-in-light-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert light mode indicator", async () => {
      const target = page.locator("#current-status-pill");
      await expect(target, "Indicator is visible in light mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-visual-consistency-spec", "assert-light-mode-indicator.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Toggle to dark mode", async () => {
      const target = page.locator("#dark-mode-toggle");
      await expect(target, "Theme is switched to dark mode.").toBeVisible();
      await expect(target, "Theme is switched to dark mode.").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-visual-consistency-spec", "toggle-to-dark-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert dark mode indicator", async () => {
      const target = page.locator("#current-status-pill");
      await expect(target, "Indicator is visible in dark mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-visual-consistency-spec", "assert-dark-mode-indicator.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
