import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Test Run Indicator", () => {
  test("Verify indicator visual state in light and dark modes", async ({ page }) => {
    await test.step("Load Intent Studio Light Mode", async () => {
      await page.goto(new URL("/?dark=false", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio loads in light mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "load-intent-studio-light-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Fill Prompt", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt is filled to enable the submit button.").toBeVisible();
      await target.fill("Theme test for indicator");
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "fill-prompt.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Generate Draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Draft is generated.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Scoping Draft Ready", async () => {
      const target = page.locator("text=Scoping IDD draft ready.");
      await expect(target, "The scoping draft is ready for approval before execution starts.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "scoping-draft-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Start Execution", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "Execution starts.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "start-execution.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert Light Mode Indicator", async () => {
      const target = page.locator("#current-status-pill");
      await expect(target, "Indicator is visible in light mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "assert-light-mode-indicator.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Toggle Dark Mode", async () => {
      const target = page.locator("#dark-mode-toggle");
      await expect(target, "Dark mode is activated via the UI toggle.").toBeVisible();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "toggle-dark-mode.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert Dark Mode Indicator", async () => {
      const target = page.locator("#current-status-pill");
      await expect(target, "Indicator is visible in dark mode.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-indicator-visual-state-in-light-and-dark-modes-spec", "assert-dark-mode-indicator.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
