import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "playwright/test";

// Generated by Intent POC. The source-scoped screenshot subtree is overwritten in place when this tracked spec is regenerated.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

test.describe("Intent Studio Status Indicator", () => {
  test("Verify status indicator real-time execution states", async ({ page }) => {
    test.setTimeout(135000);
    await test.step("Navigate to Intent Studio", async () => {
      await page.goto(new URL("/", baseUrl).toString(), { waitUntil: "domcontentloaded" });
      await expect(page.locator("body"), "Studio is loaded and prompt input is ready.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "navigate-to-intent-studio.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Enter prompt text", async () => {
      const target = page.locator("#prompt-input");
      await expect(target, "Prompt input is populated to enable the run button.").toBeVisible();
      await target.fill("Generate a test for the login flow");
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "enter-prompt-text.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Workflow Readiness Ready", async () => {
      await page.waitForSelector("#workflow-readiness-status", { timeout: 30000 });
      const target = page.locator("#workflow-readiness-status").first();
      await expect(target, "The Studio workflow readiness resolves before the run button is used.").toBeVisible({ timeout: 30000 });
      await expect(target, "The Studio workflow readiness resolves before the run button is used.").toHaveAttribute("class", new RegExp("target-ready"), { timeout: 30000 });
      const attributeValue = await target.getAttribute("class");
      expect(attributeValue, "The Studio workflow readiness resolves before the run button is used.").toBeTruthy();
      expect(attributeValue ?? "", "The Studio workflow readiness resolves before the run button is used.").toContain("target-ready");
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "workflow-readiness-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("First click to generate draft", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "The draft generation process is initiated.").toBeVisible();
      await expect(target, "The draft generation process is initiated.").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "first-click-to-generate-draft.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Scoping Draft Ready", async () => {
      const target = page.locator("text=Scoping IDD draft ready.");
      await expect(target, "The scoping draft is ready for approval before execution starts.").toBeVisible({ timeout: 30000 });
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "scoping-draft-ready.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Second click to approve and run", async () => {
      const target = page.locator("[data-testid='run-tests-button']");
      await expect(target, "The execution process is started.").toBeVisible();
      await expect(target, "The execution process is started.").toBeEnabled();
      await target.click();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "second-click-to-approve-and-run.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
    await test.step("Assert running state", async () => {
      const target = page.locator("[data-testid='test-status-indicator']:has-text('RUNNING')");
      await expect(target, "The status indicator shows the running state code.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-status-indicator-execution-spec", "assert-running-state.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
