import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test, type Page } from "playwright/test";

// Generated by Intent POC. This tracked Playwright spec is regenerated in place when the same intent path is requested.
const baseUrl = process.env.INTENT_POC_BASE_URL ?? "http://127.0.0.1:6006";
const screenshotRoot = process.env.INTENT_POC_E2E_SCREENSHOT_ROOT ?? "/home/andre/Desktop/GeniusMonkey/Intent POC/artifacts/library/intent-poc-app";

const requiredUiStates = [
  {
    "stateId": "theme-mode",
    "label": "Theme mode",
    "description": "The demo app supports light and dark theme states that affect visual evidence.",
    "requestedValue": "dark",
    "activation": [
      {
        "type": "ui-control",
        "target": "[data-testid='theme-toggle']",
        "values": {
          "light": "false",
          "dark": "true"
        },
        "notes": []
      }
    ],
    "verificationStrategies": [
      "ui-interaction-playwright"
    ],
    "notes": [
      "Verify the requested UI state before trusting screenshot evidence."
    ],
    "reason": "Prompt requests the Theme mode UI state with value \"dark\"."
  }
] as const;

function buildUrlWithUiStates(routePath: string, requirements: typeof requiredUiStates): string {
  const url = new URL(routePath, baseUrl);
  for (const requirement of requirements) {
    if (!requirement.requestedValue) {
      continue;
    }

    for (const activation of requirement.activation) {
      if (activation.type !== "query-param" || !activation.target) {
        continue;
      }

      const activationValue = activation.values[requirement.requestedValue];
      if (typeof activationValue === "string" && activationValue.length > 0) {
        url.searchParams.set(activation.target, activationValue);
      }
    }
  }

  return url.toString();
}

async function applyUiStateRequirements(page: Page, requirements: typeof requiredUiStates): Promise<void> {
  for (const requirement of requirements) {
    if (!requirement.requestedValue) {
      continue;
    }

    for (const activation of requirement.activation) {
      if (activation.type !== "ui-control" || !activation.target) {
        continue;
      }

      const activationValue = activation.values[requirement.requestedValue];
      if (!activationValue || !/^(true|1|on|enabled|active)$/i.test(activationValue)) {
        continue;
      }

      const control = page.locator(activation.target).first();
      await expect(control, `${requirement.label ?? requirement.stateId} control should be visible before activation.`).toBeVisible();
      await control.click();
    }
  }
}

test.describe("Intent-driven flow for intent-poc-app", () => {
  test("Verify dark mode input field readability", async ({ page }) => {
    await test.step("Input Field Ready For Text Entry", async () => {
      await page.goto(buildUrlWithUiStates("/library/primitive-input-field", requiredUiStates), { waitUntil: "load" });
      await page.waitForSelector("[data-testid='primitive-input-field']");
      await applyUiStateRequirements(page, requiredUiStates);
      const target = page.locator("[data-testid='primitive-input-field']");
      await expect(target, "Verify dark mode input field readability.").toBeVisible();
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-dark-mode-input-field-readability", "input-field-ready-for-text-entry.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await target.screenshot({ path: screenshotPath });
    });

    await test.step("Typed Input Text Visible", async () => {
      await page.waitForSelector("[data-testid='primitive-input-field'] input");
      const target = page.locator("[data-testid='primitive-input-field'] input");
      await expect(target, "Typed text remains visible and reviewable after the input field is activated.").toBeVisible();
      await target.fill("Readable dark mode sample text");
      const screenshotPath = path.join(screenshotRoot, "bdd/verify-dark-mode-input-field-readability", "typed-input-text-visible.png");
      await mkdir(path.dirname(screenshotPath), { recursive: true });
      await page.screenshot({ path: screenshotPath, fullPage: true });
    });
  });
});
