import path from "node:path";
import { promises as fs } from "node:fs";
import { AppConfig, RunMode } from "../config/schema";
import { CaptureOutcome } from "../capture/capture-target";
import { copyFile, ensureDirectory, pathExists, readJsonFile } from "../shared/fs";
import { hashFile } from "./hash-image";
import { generatePixelDiff } from "./pixel-diff";

export type ComparisonStatus =
  | "baseline-written"
  | "unchanged"
  | "changed"
  | "missing-baseline"
  | "capture-failed"
  | "diff-error";

export interface ComparisonItem {
  captureId: string;
  status: ComparisonStatus;
  baselinePath?: string;
  currentPath?: string;
  baselineHash?: string;
  currentHash?: string;
  diffImagePath?: string;
  diffPixels?: number;
  diffRatio?: number;
  note?: string;
}

export interface ComparisonSummary {
  mode: RunMode;
  hasDrift: boolean;
  counts: Record<ComparisonStatus, number>;
  items: ComparisonItem[];
}

interface BaselineLibraryManifest {
  mode?: RunMode;
  runId?: string;
}

function initializeCounts(): Record<ComparisonStatus, number> {
  return {
    "baseline-written": 0,
    unchanged: 0,
    changed: 0,
    "missing-baseline": 0,
    "capture-failed": 0,
    "diff-error": 0
  };
}

async function copyCapturesToBaseline(captures: CaptureOutcome[], baselineRoot: string): Promise<ComparisonItem[]> {
  const items: ComparisonItem[] = [];
  for (const capture of captures) {
    if (capture.status !== "captured") {
      items.push({
        captureId: capture.captureId,
        status: "capture-failed",
        currentPath: capture.outputPath,
        note: capture.error
      });
      continue;
    }

    const relativePath = capture.relativeOutputPath ?? `${capture.captureId}.png`;
    const baselinePath = path.join(baselineRoot, relativePath);
    await ensureDirectory(path.dirname(baselinePath));
    await copyFile(capture.outputPath, baselinePath);
    items.push({
      captureId: capture.captureId,
      status: "baseline-written",
      baselinePath,
      currentPath: capture.outputPath,
      currentHash: capture.hash,
      baselineHash: capture.hash
    });
  }

  return items;
}

export function resolveMissingBaselinePolicy(
  config: AppConfig,
  mode: RunMode
): AppConfig["comparison"]["onMissingBaseline"] {
  return mode === "compare" ? "error" : config.comparison.onMissingBaseline;
}

async function validateCompareBaselineRoot(mode: RunMode, baselineRoot: string): Promise<void> {
  if (mode !== "compare") {
    return;
  }

  const manifest = await readJsonFile<BaselineLibraryManifest>(path.join(baselineRoot, "manifest.json"));
  if (manifest?.mode === "compare") {
    const runIdSuffix = manifest.runId ? ` from run '${manifest.runId}'` : "";
    throw new Error(
      `Compare mode cannot use a baseline library whose manifest was generated by compare mode${runIdSuffix}. Regenerate the baseline in baseline mode first.`
    );
  }
}

export async function runComparison(
  config: AppConfig,
  mode: RunMode,
  captures: CaptureOutcome[],
  baselineRoot: string,
  diffDir: string
): Promise<ComparisonSummary> {
  const counts = initializeCounts();
  const missingBaselinePolicy = resolveMissingBaselinePolicy(config, mode);

  if (mode === "baseline" || mode === "approve-baseline") {
    const items = await copyCapturesToBaseline(captures, baselineRoot);
    for (const item of items) {
      counts[item.status] += 1;
    }

    return {
      mode,
      hasDrift: false,
      counts,
      items
    };
  }

  await validateCompareBaselineRoot(mode, baselineRoot);

  const items: ComparisonItem[] = [];
  for (const capture of captures) {
    if (capture.status !== "captured") {
      items.push({
        captureId: capture.captureId,
        status: "capture-failed",
        currentPath: capture.outputPath,
        note: capture.error
      });
      counts["capture-failed"] += 1;
      continue;
    }

    const baselinePath = path.join(baselineRoot, capture.relativeOutputPath ?? `${capture.captureId}.png`);
    const baselineExists = await pathExists(baselinePath);

    if (!baselineExists) {
      if (missingBaselinePolicy === "bootstrap") {
        await ensureDirectory(path.dirname(baselinePath));
        await copyFile(capture.outputPath, baselinePath);
        items.push({
          captureId: capture.captureId,
          status: "baseline-written",
          baselinePath,
          currentPath: capture.outputPath,
          baselineHash: capture.hash,
          currentHash: capture.hash,
          note: "Baseline was missing and has been bootstrapped from the current run."
        });
        counts["baseline-written"] += 1;
      } else {
        items.push({
          captureId: capture.captureId,
          status: "missing-baseline",
          currentPath: capture.outputPath,
          currentHash: capture.hash,
          note:
            mode === "compare" && config.comparison.onMissingBaseline === "bootstrap"
              ? "Baseline image not found. Compare mode keeps the baseline library read-only; rerun in baseline mode to seed it."
              : "Baseline image not found."
        });
        counts["missing-baseline"] += 1;
      }

      continue;
    }

    const baselineHash = await hashFile(baselinePath);
    if (baselineHash === capture.hash) {
      items.push({
        captureId: capture.captureId,
        status: "unchanged",
        baselinePath,
        currentPath: capture.outputPath,
        baselineHash,
        currentHash: capture.hash
      });
      counts.unchanged += 1;
      continue;
    }

    try {
      const diffImagePath = path.join(diffDir, `${capture.captureId}.png`);
      const diff = await generatePixelDiff(
        baselinePath,
        capture.outputPath,
        diffImagePath,
        config.comparison.pixelThreshold,
        config.comparison.writeDiffImages
      );

      items.push({
        captureId: capture.captureId,
        status: "changed",
        baselinePath,
        currentPath: capture.outputPath,
        baselineHash,
        currentHash: capture.hash,
        diffImagePath: diff.outputPath,
        diffPixels: diff.diffPixels,
        diffRatio: diff.diffRatio,
        note: diff.note
      });
      counts.changed += 1;
    } catch (error) {
      items.push({
        captureId: capture.captureId,
        status: "diff-error",
        baselinePath,
        currentPath: capture.outputPath,
        baselineHash,
        currentHash: capture.hash,
        note: error instanceof Error ? error.message : String(error)
      });
      counts["diff-error"] += 1;
    }
  }

  return {
    mode,
    hasDrift: counts.changed > 0 || counts["missing-baseline"] > 0 || counts["diff-error"] > 0,
    counts,
    items
  };
}