import path from "node:path";
import { NormalizedIntent, PlaywrightCheckpoint, PlaywrightSpecArtifact } from "../intent/intent-types";
import { ensureDirectory, removeDirectory, sanitizeFileSegment, writeTextFile } from "../shared/fs";
import { ResolvedSourceWorkspace } from "../target/resolve-target";

export interface GeneratedPlaywrightSpecBundle {
  outputDir: string;
  sourceDir: string;
  files: string[];
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function sanitizeOutputFileName(input: string, fallback: string): string {
  return `${sanitizeFileSegment(input) || fallback}.png`;
}

function buildCheckpointLines(checkpoint: PlaywrightCheckpoint, index: number): string[] {
  const screenshotName = sanitizeOutputFileName(checkpoint.screenshotId, `checkpoint-${index + 1}`);
  const lines = [
    `    await test.step(${quote(checkpoint.label)}, async () => {`
  ];

  if (checkpoint.action === "goto") {
    lines.push(
      `      await page.goto(new URL(${quote(checkpoint.path ?? "/")}, baseUrl).toString(), { waitUntil: "networkidle" });`
    );
  }

  if (checkpoint.waitForSelector) {
    lines.push(`      await page.waitForSelector(${quote(checkpoint.waitForSelector)});`);
  }

  if (checkpoint.action === "click" || checkpoint.action === "fill" || checkpoint.action === "assert-visible") {
    lines.push(`      const target = page.locator(${quote(checkpoint.target ?? checkpoint.locator ?? "body")});`);
    lines.push(`      await expect(target, ${quote(checkpoint.assertion)}).toBeVisible();`);

    if (checkpoint.action === "click") {
      lines.push(`      await target.click();`);
    }

    if (checkpoint.action === "fill") {
      lines.push(`      await target.fill(${quote(checkpoint.value ?? "")});`);
    }

    lines.push(`      await page.screenshot({ path: testInfo.outputPath(${quote(screenshotName)}), fullPage: true });`);
    lines.push(`    });`);
    return lines;
  }

  if (checkpoint.locator) {
    lines.push(`      const target = page.locator(${quote(checkpoint.locator)});`);
    lines.push(`      await expect(target, ${quote(checkpoint.assertion)}).toBeVisible();`);
    lines.push(`      await target.screenshot({ path: testInfo.outputPath(${quote(screenshotName)}) });`);
    lines.push(`    });`);
    return lines;
  }

  lines.push(`      await expect(page.locator("body"), ${quote(checkpoint.assertion)}).toBeVisible();`);
  lines.push(`      await page.screenshot({ path: testInfo.outputPath(${quote(screenshotName)}), fullPage: true });`);
  lines.push(`    });`);
  return lines;
}

function buildSpecFile(spec: PlaywrightSpecArtifact, baseUrl: string): string {
  const lines = [
    "import { expect, test } from \"playwright/test\";",
    "",
    "// Generated by Intent POC. The source-specific subtree is fully overwritten on regeneration.",
    `const baseUrl = process.env.INTENT_POC_BASE_URL ?? ${quote(baseUrl)};`,
    "",
    `test.describe(${quote(spec.suiteName)}, () => {`,
    `  test(${quote(spec.testName)}, async ({ page }, testInfo) => {`
  ];

  for (const [index, checkpoint] of spec.checkpoints.entries()) {
    lines.push(...buildCheckpointLines(checkpoint, index));
  }

  lines.push("  });");
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

function resolveSpecOutputPath(outputDir: string, relativeSpecPath: string): string {
  if (path.isAbsolute(relativeSpecPath)) {
    throw new Error(`Generated Playwright spec path must be relative: ${relativeSpecPath}`);
  }

  const normalizedRelativePath = path.normalize(relativeSpecPath);
  if (normalizedRelativePath === ".." || normalizedRelativePath.startsWith(`..${path.sep}`)) {
    throw new Error(`Generated Playwright spec path cannot escape the configured output root: ${relativeSpecPath}`);
  }

  return path.join(outputDir, normalizedRelativePath);
}

function collectSourceSpecs(normalizedIntent: NormalizedIntent, sourceId: string): PlaywrightSpecArtifact[] {
  const specsByPath = new Map<string, PlaywrightSpecArtifact>();

  for (const workItem of normalizedIntent.businessIntent.workItems) {
    for (const spec of workItem.playwright.specs) {
      if (spec.sourceId !== sourceId) {
        continue;
      }

      if (!specsByPath.has(spec.relativeSpecPath)) {
        specsByPath.set(spec.relativeSpecPath, spec);
      }
    }
  }

  return Array.from(specsByPath.values()).sort((left, right) => left.relativeSpecPath.localeCompare(right.relativeSpecPath));
}

export async function writeGeneratedPlaywrightTests(input: {
  workspace: ResolvedSourceWorkspace;
  normalizedIntent: NormalizedIntent;
  sourceId: string;
}): Promise<GeneratedPlaywrightSpecBundle | null> {
  if (!input.workspace.source.testing.playwright.enabled) {
    return null;
  }

  const specs = collectSourceSpecs(input.normalizedIntent, input.sourceId);
  if (specs.length === 0) {
    return null;
  }

  const outputDir = path.resolve(input.workspace.rootDir, input.workspace.source.testing.playwright.outputDir);
  const sourceDir = path.join(outputDir, sanitizeFileSegment(input.sourceId) || input.sourceId);

  await removeDirectory(sourceDir);
  await ensureDirectory(sourceDir);

  const files: string[] = [];

  for (const spec of specs) {
    const outputPath = resolveSpecOutputPath(outputDir, spec.relativeSpecPath);
    await writeTextFile(outputPath, buildSpecFile(spec, input.workspace.source.app.baseUrl));
    files.push(outputPath);
  }

  return {
    outputDir,
    sourceDir,
    files
  };
}