import { SurfaceDefinition } from "./types";

export const SURFACE_CATALOG: SurfaceDefinition[] = [
  { id: "primitive-color-chip", title: "Color Chip", testId: "primitive-color-chip", layer: "primitive", changesInV2: true },
  { id: "primitive-typography", title: "Typography Scale", testId: "primitive-typography", layer: "primitive", changesInV2: true },
  { id: "primitive-pill-tag", title: "Pill Tag", testId: "primitive-pill-tag", layer: "primitive", changesInV2: true },
  { id: "primitive-input-field", title: "Input Field", testId: "primitive-input-field", layer: "primitive", changesInV2: true },
  { id: "primitive-button-set", title: "Button Set", testId: "primitive-button-set", layer: "primitive", changesInV2: true },
  { id: "primitive-avatar-stack", title: "Avatar Stack", testId: "primitive-avatar-stack", layer: "primitive", changesInV2: true },
  { id: "primitive-status-indicator", title: "Status Indicator", testId: "primitive-status-indicator", layer: "primitive", changesInV2: true },
  { id: "primitive-spacing-scale", title: "Spacing Scale", testId: "primitive-spacing-scale", layer: "primitive", changesInV2: true },
  { id: "primitive-icon-list", title: "Icon List", testId: "primitive-icon-list", layer: "primitive", changesInV2: true },
  { id: "primitive-kpi-block", title: "KPI Block", testId: "primitive-kpi-block", layer: "primitive", changesInV2: true },

  { id: "component-button-primary", title: "Primary Button", testId: "component-button-primary", layer: "component", changesInV2: true },
  { id: "component-button-secondary", title: "Secondary Button", testId: "component-button-secondary", layer: "component", changesInV2: true },
  { id: "component-button-danger", title: "Danger Button", testId: "component-button-danger", layer: "component", changesInV2: true },
  { id: "component-card-highlight", title: "Highlight Card", testId: "component-card-highlight", layer: "component", changesInV2: true },
  { id: "component-card-compact", title: "Compact Card", testId: "component-card-compact", layer: "component", changesInV2: true },
  { id: "component-banner-info", title: "Info Banner", testId: "component-banner-info", layer: "component", changesInV2: true },
  { id: "component-banner-warning", title: "Warning Banner", testId: "component-banner-warning", layer: "component", changesInV2: true },
  { id: "component-modal-shell", title: "Modal Shell", testId: "component-modal-shell", layer: "component", changesInV2: true },
  { id: "component-table-row", title: "Table Row", testId: "component-table-row", layer: "component", changesInV2: true },
  { id: "component-search-bar", title: "Search Bar", testId: "component-search-bar", layer: "component", changesInV2: true },
  { id: "component-stat-tile", title: "Stat Tile", testId: "component-stat-tile", layer: "component", changesInV2: true },
  { id: "component-nav-tabs", title: "Nav Tabs", testId: "component-nav-tabs", layer: "component", changesInV2: true },
  { id: "component-toast-success", title: "Success Toast", testId: "component-toast-success", layer: "component", changesInV2: true },
  { id: "component-toast-error", title: "Error Toast", testId: "component-toast-error", layer: "component", changesInV2: true },
  { id: "component-form-section", title: "Form Section", testId: "component-form-section", layer: "component", changesInV2: true },
  { id: "component-user-list-item", title: "User List Item", testId: "component-user-list-item", layer: "component", changesInV2: true },
  { id: "component-activity-timeline", title: "Activity Timeline", testId: "component-activity-timeline", layer: "component", changesInV2: true },

  { id: "view-dashboard-summary", title: "Dashboard Summary View", testId: "view-dashboard-summary", layer: "view", changesInV2: true },
  { id: "view-list-overview", title: "List Overview View", testId: "view-list-overview", layer: "view", changesInV2: true },
  { id: "view-settings-panel", title: "Settings Panel View", testId: "view-settings-panel", layer: "view", changesInV2: true },
  { id: "view-empty-results", title: "Empty Results View", testId: "view-empty-results", layer: "view", changesInV2: true },
  { id: "view-campaign-table", title: "Campaign Table View", testId: "view-campaign-table", layer: "view", changesInV2: true },
  { id: "view-notifications-center", title: "Notifications Center View", testId: "view-notifications-center", layer: "view", changesInV2: true },
  { id: "view-user-directory", title: "User Directory View", testId: "view-user-directory", layer: "view", changesInV2: true },
  { id: "view-revenue-kpis", title: "Revenue KPIs View", testId: "view-revenue-kpis", layer: "view", changesInV2: true },
  { id: "view-onboarding-checklist", title: "Onboarding Checklist View", testId: "view-onboarding-checklist", layer: "view", changesInV2: true },
  { id: "view-approval-queue", title: "Approval Queue View", testId: "view-approval-queue", layer: "view", changesInV2: true },
  { id: "view-audit-log", title: "Audit Log View", testId: "view-audit-log", layer: "view", changesInV2: true },
  { id: "view-billing-overview", title: "Billing Overview View", testId: "view-billing-overview", layer: "view", changesInV2: true },

  { id: "page-analytics-overview", title: "Analytics Overview Page", testId: "page-analytics-overview", layer: "page", changesInV2: true },
  { id: "page-account-list", title: "Account List Page", testId: "page-account-list", layer: "page", changesInV2: true },
  { id: "page-campaign-editor", title: "Campaign Editor Page", testId: "page-campaign-editor", layer: "page", changesInV2: true },
  { id: "page-system-settings", title: "System Settings Page", testId: "page-system-settings", layer: "page", changesInV2: true },
  { id: "page-operations-center", title: "Operations Center Page", testId: "page-operations-center", layer: "page", changesInV2: true },
  { id: "page-user-management", title: "User Management Page", testId: "page-user-management", layer: "page", changesInV2: true },
  { id: "page-incident-review", title: "Incident Review Page", testId: "page-incident-review", layer: "page", changesInV2: true },
  { id: "page-revenue-forecast", title: "Revenue Forecast Page", testId: "page-revenue-forecast", layer: "page", changesInV2: true }
];