import { strict as assert } from "node:assert";
import path from "node:path";
import test from "node:test";
import { normalizeIntent } from "../intent/normalize-intent";
import {
  buildBehaviorTestConfig,
  buildCapturedOutcome,
  buildComparisonSummary,
  buildIntentPocAppBehaviorSource
} from "../orchestrator/run-intent.test-support";
import { SourceRunPaths } from "./paths";
import { buildSourceSummaryMarkdown } from "./write-summary";

function buildSourcePaths(rootDir: string): SourceRunPaths {
  const sourceDir = path.join(rootDir, "artifacts", "runs", "run-1", "sources", "intent-poc-app");

  return {
    controllerRoot: rootDir,
    runId: "run-1",
    sourceId: "intent-poc-app",
    sourceDir,
    attemptsDir: path.join(sourceDir, "attempts"),
    capturesDir: path.join(sourceDir, "captures"),
    diffsDir: path.join(sourceDir, "diffs"),
    logsDir: path.join(sourceDir, "logs"),
    manifestPath: path.join(sourceDir, "manifest.json"),
    hashesPath: path.join(sourceDir, "hashes.json"),
    comparisonPath: path.join(sourceDir, "comparison.json"),
    summaryPath: path.join(sourceDir, "summary.md"),
    appLogPath: path.join(sourceDir, "logs", "app.log"),
    baselineSourceDir: path.join(rootDir, "artifacts", "library", "intent-poc-app")
  };
}

test("buildSourceSummaryMarkdown surfaces capture coverage and missing baseline issues", () => {
  const rootDir = "/tmp/intent-poc-summary";
  const config = buildBehaviorTestConfig(rootDir, {
    sources: {
      "intent-poc-app": buildIntentPocAppBehaviorSource(rootDir)
    },
    defaultSourceId: "intent-poc-app"
  });
  const normalizedIntent = normalizeIntent({
    rawPrompt: "Compare the intent-poc-app evidence so we can tell whether the dark mode work is visible.",
    defaultSourceId: "intent-poc-app",
    continueOnCaptureError: false,
    availableSources: config.sources
  });
  normalizedIntent.executionPlan.sources[0]!.warnings = [
    "Gemini suggested narrowing intent-poc-app captures to library-index, but the prompt did not explicitly name those captures, so all configured captures were preserved."
  ];

  const markdown = buildSourceSummaryMarkdown({
    config,
    paths: buildSourcePaths(rootDir),
    normalizedIntent,
    linearIssue: null,
    captures: [buildCapturedOutcome(rootDir, "library-index")],
    comparison: buildComparisonSummary({
      hasDrift: true,
      counts: { "missing-baseline": 1 },
      items: [
        {
          captureId: "library-index",
          status: "missing-baseline",
          currentPath: path.join(rootDir, "captures", "library-index.png"),
          currentHash: "library-index-hash",
          note: "Baseline image not found."
        }
      ]
    }),
    status: "failed",
    error: "One or more captures are missing a baseline image.",
    attempts: []
  });

  assert.match(markdown, /Configured captures: 3/);
  assert.match(markdown, /Executed captures: 1/);
  assert.match(markdown, /Gemini suggested narrowing intent-poc-app captures to library-index/);
  assert.match(markdown, /## Comparison Issues/);
  assert.match(markdown, /One or more captures are missing a baseline image\./);
  assert.match(markdown, /Missing baseline for library-index: Baseline image not found\./);
});

test("buildSourceSummaryMarkdown surfaces invalid baseline preflight failures", () => {
  const rootDir = "/tmp/intent-poc-summary";
  const config = buildBehaviorTestConfig(rootDir, {
    sources: {
      "intent-poc-app": buildIntentPocAppBehaviorSource(rootDir)
    },
    defaultSourceId: "intent-poc-app"
  });
  const normalizedIntent = normalizeIntent({
    rawPrompt: "Compare the intent-poc-app evidence so we can tell whether the dark mode work is visible.",
    defaultSourceId: "intent-poc-app",
    continueOnCaptureError: false,
    availableSources: config.sources
  });

  const markdown = buildSourceSummaryMarkdown({
    config,
    paths: buildSourcePaths(rootDir),
    normalizedIntent,
    linearIssue: null,
    captures: [],
    status: "failed",
    error: "Compare mode cannot use a baseline library whose manifest was generated by compare mode from run 'compare-tainted-run'. Regenerate the baseline in baseline mode first.",
    attempts: []
  });

  assert.match(markdown, /## Comparison Issues/);
  assert.match(markdown, /manifest was generated by compare mode/);
});

test("buildSourceSummaryMarkdown labels targeted code-validation work items correctly", () => {
  const rootDir = "/tmp/intent-poc-summary";
  const config = buildBehaviorTestConfig(rootDir, {
    sources: {
      "intent-poc-app": buildIntentPocAppBehaviorSource(rootDir)
    },
    defaultSourceId: "intent-poc-app"
  });
  const normalizedIntent = normalizeIntent({
    rawPrompt:
      "the planner needs to keep source-lane distribution summaries aligned with linear publishing without changing the Studio UI.",
    defaultSourceId: "intent-poc-app",
    continueOnCaptureError: false,
    availableSources: config.sources
  });

  const paths = {
    ...buildSourcePaths(rootDir),
    sourceId: "intent-poc-app",
    sourceDir: path.join(rootDir, "artifacts", "runs", "run-1", "sources", "intent-poc-app")
  };

  const markdown = buildSourceSummaryMarkdown({
    config,
    paths,
    normalizedIntent,
    linearIssue: null,
    captures: [],
    status: "planned",
    attempts: []
  });

  assert.match(markdown, /Targeted code validation work item/);
});

test("buildSourceSummaryMarkdown labels mocked-state Playwright work items clearly", () => {
  const rootDir = "/tmp/intent-poc-summary";
  const config = buildBehaviorTestConfig(rootDir, {
    sources: {
      "intent-poc-app": buildIntentPocAppBehaviorSource(rootDir)
    },
    defaultSourceId: "intent-poc-app"
  });
  const normalizedIntent = normalizeIntent({
    rawPrompt:
      "the intent lifecycle needs to map the execution plan better and support state reversion when the model calls a rerun on a step.",
    defaultSourceId: "intent-poc-app",
    continueOnCaptureError: false,
    availableSources: config.sources
  });

  const paths = {
    ...buildSourcePaths(rootDir),
    sourceId: "intent-poc-app",
    sourceDir: path.join(rootDir, "artifacts", "runs", "run-1", "sources", "intent-poc-app")
  };

  const markdown = buildSourceSummaryMarkdown({
    config,
    paths,
    normalizedIntent,
    linearIssue: null,
    captures: [],
    status: "planned",
    attempts: []
  });

  assert.match(markdown, /QA-runnable Playwright spec with mocked Studio app state/);
  assert.match(markdown, /mocked Studio app state/);
});