import { strict as assert } from "node:assert";
import path from "node:path";
import test from "node:test";
import { normalizeIntent } from "../intent/normalize-intent";
import {
  buildBehaviorTestConfig,
  buildCapturedOutcome,
  buildComparisonSummary,
  buildDemoCatalogBehaviorSource
} from "../orchestrator/run-intent.test-support";
import { SourceRunPaths } from "./paths";
import { buildSourceSummaryMarkdown } from "./write-summary";

function buildSourcePaths(rootDir: string): SourceRunPaths {
  const sourceDir = path.join(rootDir, "artifacts", "runs", "run-1", "sources", "demo-catalog");

  return {
    controllerRoot: rootDir,
    runId: "run-1",
    sourceId: "demo-catalog",
    sourceDir,
    attemptsDir: path.join(sourceDir, "attempts"),
    capturesDir: path.join(sourceDir, "captures"),
    diffsDir: path.join(sourceDir, "diffs"),
    logsDir: path.join(sourceDir, "logs"),
    manifestPath: path.join(sourceDir, "manifest.json"),
    hashesPath: path.join(sourceDir, "hashes.json"),
    comparisonPath: path.join(sourceDir, "comparison.json"),
    summaryPath: path.join(sourceDir, "summary.md"),
    appLogPath: path.join(sourceDir, "logs", "app.log"),
    baselineSourceDir: path.join(rootDir, "artifacts", "library", "demo-catalog")
  };
}

test("buildSourceSummaryMarkdown surfaces capture coverage and missing baseline issues", () => {
  const rootDir = "/tmp/intent-poc-summary";
  const config = buildBehaviorTestConfig(rootDir, {
    sources: {
      "demo-catalog": buildDemoCatalogBehaviorSource(rootDir)
    },
    defaultSourceId: "demo-catalog"
  });
  const normalizedIntent = normalizeIntent({
    rawPrompt: "Compare the demo-catalog evidence so we can tell whether the dark mode work is visible.",
    defaultSourceId: "demo-catalog",
    continueOnCaptureError: false,
    availableSources: config.sources
  });
  normalizedIntent.executionPlan.sources[0]!.warnings = [
    "Gemini suggested narrowing demo-catalog captures to library-index, but the prompt did not explicitly name those captures, so all configured captures were preserved."
  ];

  const markdown = buildSourceSummaryMarkdown({
    config,
    paths: buildSourcePaths(rootDir),
    normalizedIntent,
    linearIssue: null,
    captures: [buildCapturedOutcome(rootDir, "library-index")],
    comparison: buildComparisonSummary({
      hasDrift: true,
      counts: { "missing-baseline": 1 },
      items: [
        {
          captureId: "library-index",
          status: "missing-baseline",
          currentPath: path.join(rootDir, "captures", "library-index.png"),
          currentHash: "library-index-hash",
          note: "Baseline image not found."
        }
      ]
    }),
    status: "failed",
    error: "One or more captures are missing a baseline image.",
    attempts: []
  });

  assert.match(markdown, /Configured captures: 3/);
  assert.match(markdown, /Executed captures: 1/);
  assert.match(markdown, /Gemini suggested narrowing demo-catalog captures to library-index/);
  assert.match(markdown, /## Comparison Issues/);
  assert.match(markdown, /One or more captures are missing a baseline image\./);
  assert.match(markdown, /Missing baseline for library-index: Baseline image not found\./);
});

test("buildSourceSummaryMarkdown surfaces invalid baseline preflight failures", () => {
  const rootDir = "/tmp/intent-poc-summary";
  const config = buildBehaviorTestConfig(rootDir, {
    sources: {
      "demo-catalog": buildDemoCatalogBehaviorSource(rootDir)
    },
    defaultSourceId: "demo-catalog"
  });
  const normalizedIntent = normalizeIntent({
    rawPrompt: "Compare the demo-catalog evidence so we can tell whether the dark mode work is visible.",
    defaultSourceId: "demo-catalog",
    continueOnCaptureError: false,
    availableSources: config.sources
  });

  const markdown = buildSourceSummaryMarkdown({
    config,
    paths: buildSourcePaths(rootDir),
    normalizedIntent,
    linearIssue: null,
    captures: [],
    status: "failed",
    error: "Compare mode cannot use a baseline library whose manifest was generated by compare mode from run 'compare-tainted-run'. Regenerate the baseline in baseline mode first.",
    attempts: []
  });

  assert.match(markdown, /## Comparison Issues/);
  assert.match(markdown, /manifest was generated by compare mode/);
});